var hierarchy =
[
    [ "_CPConcreteMutableSet", null, [
      [ "CPCountedSet", "interface_c_p_counted_set.html", null ]
    ] ],
    [ "_CPMultipleValueActionBinding", null, [
      [ "CPActionBinding", "interface_c_p_action_binding.html", null ],
      [ "CPDoubleClickActionBinding", "interface_c_p_double_click_action_binding.html", null ]
    ] ],
    [ "_CPMultipleValueBooleanBinding", null, [
      [ "CPMultipleValueAndBinding", "class_c_p_multiple_value_and_binding.html", null ],
      [ "CPMultipleValueOrBinding", "class_c_p_multiple_value_or_binding.html", null ]
    ] ],
    [ "_CPPatternBinding", null, [
      [ "CPTitleWithPatternBinding", "class_c_p_title_with_pattern_binding.html", null ],
      [ "CPValueWithPatternBinding", "class_c_p_value_with_pattern_binding.html", null ]
    ] ],
    [ "CPAccordionViewItem(CPSynthesizedAccessors)", "category_c_p_accordion_view_item_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPAlert(CPAlertDelegate)", "category_c_p_alert_07_c_p_alert_delegate_08.html", null ],
    [ "CPAlert(CPSynthesizedAccessors)", "category_c_p_alert_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPAnimation(CPAnimationDelegate)", "category_c_p_animation_07_c_p_animation_delegate_08.html", null ],
    [ "CPApplication(CPSynthesizedAccessors)", "category_c_p_application_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPArray", null, [
      [ "CPMutableArray", "interface_c_p_mutable_array.html", null ]
    ] ],
    [ "CPArray(CPKeyValueCoding)", "category_c_p_array_07_c_p_key_value_coding_08.html", null ],
    [ "CPArray(CPMutableCopying)", "category_c_p_array_07_c_p_mutable_copying_08.html", null ],
    [ "CPArray(KeyValueObserving)", "category_c_p_array_07_key_value_observing_08.html", null ],
    [ "CPArrayController(CPBinder)", "category_c_p_array_controller_07_c_p_binder_08.html", null ],
    [ "CPArrayController(CPCoding)", "category_c_p_array_controller_07_c_p_coding_08.html", null ],
    [ "CPAttributedString(CPCoding)", "category_c_p_attributed_string_07_c_p_coding_08.html", null ],
    [ "CPBinder(CPSynthesizedAccessors)", "category_c_p_binder_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPBox(CPCoding)", "category_c_p_box_07_c_p_coding_08.html", null ],
    [ "CPBox(CPSynthesizedAccessors)", "category_c_p_box_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPBrowser(CPBrowserDelegate)", "category_c_p_browser_07_c_p_browser_delegate_08.html", null ],
    [ "CPBrowser(CPCoding)", "category_c_p_browser_07_c_p_coding_08.html", null ],
    [ "CPBrowser(CPSynthesizedAccessors)", "category_c_p_browser_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPBundle(CPCibLoading)", "category_c_p_bundle_07_c_p_cib_loading_08.html", null ],
    [ "CPButton(CPCoding)", "category_c_p_button_07_c_p_coding_08.html", null ],
    [ "CPButton(NS)", "category_c_p_button_07_n_s_08.html", null ],
    [ "CPButtonBar(CPCoding)", "category_c_p_button_bar_07_c_p_coding_08.html", null ],
    [ "CPByteCountFormatter(CPCoding)", "category_c_p_byte_count_formatter_07_c_p_coding_08.html", null ],
    [ "CPCache(CPCacheDelegate)", "category_c_p_cache_07_c_p_cache_delegate_08.html", null ],
    [ "CPCache(CPSynthesizedAccessors)", "category_c_p_cache_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPCharacterSet(CPCoding)", "category_c_p_character_set_07_c_p_coding_08.html", null ],
    [ "CPCib(CPCoding)", "category_c_p_cib_07_c_p_coding_08.html", null ],
    [ "CPCib(CPURLConnectionDelegate)", "category_c_p_cib_07_c_p_u_r_l_connection_delegate_08.html", null ],
    [ "CPCibConnector(CPCoding)", "category_c_p_cib_connector_07_c_p_coding_08.html", null ],
    [ "CPCibConnector(CPSynthesizedAccessors)", "category_c_p_cib_connector_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPClipView(CPCoding)", "category_c_p_clip_view_07_c_p_coding_08.html", null ],
    [ "<CPCoding>", "protocol_c_p_coding-p.html", null ],
    [ "CPCollectionView(CPCoding)", "category_c_p_collection_view_07_c_p_coding_08.html", null ],
    [ "CPCollectionView(CPCollectionViewDelegate)", "category_c_p_collection_view_07_c_p_collection_view_delegate_08.html", null ],
    [ "CPCollectionView(CPSynthesizedAccessors)", "category_c_p_collection_view_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPCollectionView(Deprecated)", "category_c_p_collection_view_07_deprecated_08.html", null ],
    [ "CPCollectionView(DragAndDrop)", "category_c_p_collection_view_07_drag_and_drop_08.html", null ],
    [ "CPCollectionView(KeyboardInteraction)", "category_c_p_collection_view_07_keyboard_interaction_08.html", null ],
    [ "CPColor(CoreGraphicsExtensions)", "category_c_p_color_07_core_graphics_extensions_08.html", null ],
    [ "CPColor(CPCoding)", "category_c_p_color_07_c_p_coding_08.html", null ],
    [ "CPColor(Debugging)", "category_c_p_color_07_debugging_08.html", null ],
    [ "CPColorWell(CPCoding)", "category_c_p_color_well_07_c_p_coding_08.html", null ],
    [ "CPComboBox(Bindings)", "category_c_p_combo_box_07_bindings_08.html", null ],
    [ "CPComboBox(CPCoding)", "category_c_p_combo_box_07_c_p_coding_08.html", null ],
    [ "CPComboBox(CPComboBoxDataSource)", "category_c_p_combo_box_07_c_p_combo_box_data_source_08.html", null ],
    [ "CPComboBox(CPComboBoxDelegate)", "category_c_p_combo_box_07_c_p_combo_box_delegate_08.html", null ],
    [ "CPComparisonPredicate(CPCoding)", "category_c_p_comparison_predicate_07_c_p_coding_08.html", null ],
    [ "CPCompoundPredicate(CPCoding)", "category_c_p_compound_predicate_07_c_p_coding_08.html", null ],
    [ "CPControl(CPCoding)", "category_c_p_control_07_c_p_coding_08.html", null ],
    [ "CPControl(CPSynthesizedAccessors)", "category_c_p_control_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPCursor(CPCoding)", "category_c_p_cursor_07_c_p_coding_08.html", null ],
    [ "CPCursor(CPSynthesizedAccessors)", "category_c_p_cursor_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPData(CPMutableData)", "category_c_p_data_07_c_p_mutable_data_08.html", null ],
    [ "CPData(Deprecated)", "category_c_p_data_07_deprecated_08.html", null ],
    [ "CPDate(CPCoding)", "category_c_p_date_07_c_p_coding_08.html", null ],
    [ "CPDate(CPDatePickerAdditions)", "category_c_p_date_07_c_p_date_picker_additions_08.html", null ],
    [ "CPDate(CPTimeZone)", "category_c_p_date_07_c_p_time_zone_08.html", null ],
    [ "CPDateFormatter(CPCoding)", "category_c_p_date_formatter_07_c_p_coding_08.html", null ],
    [ "CPDateFormatter(CPSynthesizedAccessors)", "category_c_p_date_formatter_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPDatePicker(CPCoding)", "category_c_p_date_picker_07_c_p_coding_08.html", null ],
    [ "CPDatePicker(CPSynthesizedAccessors)", "category_c_p_date_picker_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPDecimalNumber(CPCoding)", "category_c_p_decimal_number_07_c_p_coding_08.html", null ],
    [ "<CPDecimalNumberBehaviors>", "protocol_c_p_decimal_number_behaviors-p.html", null ],
    [ "CPDecimalNumberHandler(CPCoding)", "category_c_p_decimal_number_handler_07_c_p_coding_08.html", null ],
    [ "CPDecimalNumberHandler(CPDecimalNumberBehaviors)", "category_c_p_decimal_number_handler_07_c_p_decimal_number_behaviors_08.html", null ],
    [ "CPDictionary(CPCoding)", "category_c_p_dictionary_07_c_p_coding_08.html", null ],
    [ "CPDictionary(CPKeyValueCoding)", "category_c_p_dictionary_07_c_p_key_value_coding_08.html", null ],
    [ "CPDictionary(KeyValueObserving)", "category_c_p_dictionary_07_key_value_observing_08.html", null ],
    [ "CPDictionaryController(CPCoding)", "category_c_p_dictionary_controller_07_c_p_coding_08.html", null ],
    [ "CPDictionaryController(CPSynthesizedAccessors)", "category_c_p_dictionary_controller_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPDocument(ClosingDocuments)", "category_c_p_document_07_closing_documents_08.html", null ],
    [ "CPDocumentController(Closing)", "category_c_p_document_controller_07_closing_08.html", null ],
    [ "CPDocumentController(Recents)", "category_c_p_document_controller_07_recents_08.html", null ],
    [ "CPDragServer(CPSynthesizedAccessors)", "category_c_p_drag_server_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPError(CPCoding)", "category_c_p_error_07_c_p_coding_08.html", null ],
    [ "CPEvent(CPApplicationModifierFlags)", "category_c_p_event_07_c_p_application_modifier_flags_08.html", null ],
    [ "CPException(CPCoding)", "category_c_p_exception_07_c_p_coding_08.html", null ],
    [ "CPException(CPCopying)", "category_c_p_exception_07_c_p_copying_08.html", null ],
    [ "CPFlashMovie(CPCoding)", "category_c_p_flash_movie_07_c_p_coding_08.html", null ],
    [ "CPFont(CPCoding)", "category_c_p_font_07_c_p_coding_08.html", null ],
    [ "CPFont(CPSynthesizedAccessors)", "category_c_p_font_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPFontManager(CPSynthesizedAccessors)", "category_c_p_font_manager_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPImage(CachedImage)", "category_c_p_image_07_cached_image_08.html", null ],
    [ "CPImage(CPCoding)", "category_c_p_image_07_c_p_coding_08.html", null ],
    [ "CPImageView(CPCoding)", "category_c_p_image_view_07_c_p_coding_08.html", null ],
    [ "CPIndexPath(CPCoding)", "category_c_p_index_path_07_c_p_coding_08.html", null ],
    [ "CPIndexPath(CPSynthesizedAccessors)", "category_c_p_index_path_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPIndexSet(CPCoding)", "category_c_p_index_set_07_c_p_coding_08.html", null ],
    [ "CPIndexSet(CPCopying)", "category_c_p_index_set_07_c_p_copying_08.html", null ],
    [ "CPIndexSet(CPMutableIndexSet)", "category_c_p_index_set_07_c_p_mutable_index_set_08.html", null ],
    [ "CPInvocation(CPCoding)", "category_c_p_invocation_07_c_p_coding_08.html", null ],
    [ "CPLevelIndicator(CPCoding)", "category_c_p_level_indicator_07_c_p_coding_08.html", null ],
    [ "CPLevelIndicator(CPSynthesizedAccessors)", "category_c_p_level_indicator_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPLocale(CPCoding)", "category_c_p_locale_07_c_p_coding_08.html", null ],
    [ "CPMenu(CPCoding)", "category_c_p_menu_07_c_p_coding_08.html", null ],
    [ "CPMenu(CPKeyValueCoding)", "category_c_p_menu_07_c_p_key_value_coding_08.html", null ],
    [ "CPMenu(CPKeyValueObserving)", "category_c_p_menu_07_c_p_key_value_observing_08.html", null ],
    [ "CPMenu(CPMenuDelegate)", "category_c_p_menu_07_c_p_menu_delegate_08.html", null ],
    [ "CPMenuItem(CPCoding)", "category_c_p_menu_item_07_c_p_coding_08.html", null ],
    [ "CPNinePartImage(CPCoding)", "category_c_p_nine_part_image_07_c_p_coding_08.html", null ],
    [ "CPNull(CPKeyValueCoding)", "category_c_p_null_07_c_p_key_value_coding_08.html", null ],
    [ "CPNumber(CPCoding)", "category_c_p_number_07_c_p_coding_08.html", null ],
    [ "CPNumberFormatter(CPCoding)", "category_c_p_number_formatter_07_c_p_coding_08.html", null ],
    [ "CPNumberFormatter(CPSynthesizedAccessors)", "category_c_p_number_formatter_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPObject", "class_c_p_object.html", [
      [ "CAAnimation", "interface_c_a_animation.html", [
        [ "CAPropertyAnimation", "class_c_a_property_animation.html", [
          [ "CABasicAnimation", "class_c_a_basic_animation.html", null ]
        ] ]
      ] ],
      [ "CALayer", "interface_c_a_layer.html", [
        [ "CAFlashLayer", "interface_c_a_flash_layer.html", null ]
      ] ],
      [ "CAMediaTimingFunction", "interface_c_a_media_timing_function.html", null ],
      [ "CPAccordionViewItem", "class_c_p_accordion_view_item.html", null ],
      [ "CPAlert", "interface_c_p_alert.html", null ],
      [ "CPAnimation", "interface_c_p_animation.html", [
        [ "CPViewAnimation", "interface_c_p_view_animation.html", null ]
      ] ],
      [ "CPAttributedString", "interface_c_p_attributed_string.html", [
        [ "CPMutableAttributedString", "class_c_p_mutable_attributed_string.html", null ]
      ] ],
      [ "CPBasePlatform", "interface_c_p_base_platform.html", [
        [ "CPPlatform", "interface_c_p_platform.html", null ]
      ] ],
      [ "CPBasePlatformString", "interface_c_p_base_platform_string.html", [
        [ "CPPlatformString", "interface_c_p_platform_string.html", null ]
      ] ],
      [ "CPBezierPath", "interface_c_p_bezier_path.html", null ],
      [ "CPBinder", "interface_c_p_binder.html", [
        [ "CPColorWellValueBinder", "class_c_p_color_well_value_binder.html", null ],
        [ "CPImageViewValueBinder", "class_c_p_image_view_value_binder.html", null ],
        [ "CPPredicateEditorValueBinder", "interface_c_p_predicate_editor_value_binder.html", null ],
        [ "CPTableColumnValueBinder", "class_c_p_table_column_value_binder.html", null ],
        [ "CPTableContentBinder", "interface_c_p_table_content_binder.html", null ]
      ] ],
      [ "CPBundle", "interface_c_p_bundle.html", null ],
      [ "CPCache", "interface_c_p_cache.html", null ],
      [ "CPCharacterSet", "interface_c_p_character_set.html", null ],
      [ "CPCib", "interface_c_p_cib.html", null ],
      [ "CPCibConnector", "interface_c_p_cib_connector.html", [
        [ "CPCibBindingConnector", "interface_c_p_cib_binding_connector.html", null ],
        [ "CPCibControlConnector", "interface_c_p_cib_control_connector.html", null ],
        [ "CPCibHelpConnector", "interface_c_p_cib_help_connector.html", null ],
        [ "CPCibOutletConnector", "interface_c_p_cib_outlet_connector.html", null ],
        [ "CPCibRuntimeAttributesConnector", "interface_c_p_cib_runtime_attributes_connector.html", null ]
      ] ],
      [ "CPCoder", "interface_c_p_coder.html", [
        [ "CPKeyedArchiver", "interface_c_p_keyed_archiver.html", null ],
        [ "CPKeyedUnarchiver", "interface_c_p_keyed_unarchiver.html", null ]
      ] ],
      [ "CPColor", "interface_c_p_color.html", null ],
      [ "CPColorPicker", "interface_c_p_color_picker.html", [
        [ "CPColorWheelColorPicker", "class_c_p_color_wheel_color_picker.html", null ],
        [ "CPSliderColorPicker", "interface_c_p_slider_color_picker.html", null ]
      ] ],
      [ "CPColorSpace", "interface_c_p_color_space.html", null ],
      [ "CPController", "interface_c_p_controller.html", [
        [ "CPObjectController", "interface_c_p_object_controller.html", [
          [ "CPArrayController", "interface_c_p_array_controller.html", [
            [ "CPDictionaryController", "interface_c_p_dictionary_controller.html", null ]
          ] ]
        ] ],
        [ "CPUserDefaultsController", "interface_c_p_user_defaults_controller.html", null ]
      ] ],
      [ "CPControllerSelectionProxy", "interface_c_p_controller_selection_proxy.html", null ],
      [ "CPCookie", "interface_c_p_cookie.html", null ],
      [ "CPCursor", "interface_c_p_cursor.html", null ],
      [ "CPData", "interface_c_p_data.html", null ],
      [ "CPDate", "interface_c_p_date.html", null ],
      [ "CPDecimalNumberHandler", "class_c_p_decimal_number_handler.html", null ],
      [ "CPDelayedPerform", "interface_c_p_delayed_perform.html", null ],
      [ "CPDictionary", "interface_c_p_dictionary.html", [
        [ "CPMutableDictionary", "class_c_p_mutable_dictionary.html", null ]
      ] ],
      [ "CPDocumentController", "interface_c_p_document_controller.html", null ],
      [ "CPDraggingInfo", "interface_c_p_dragging_info.html", null ],
      [ "CPDragServer", "interface_c_p_drag_server.html", null ],
      [ "CPEnumerator", "interface_c_p_enumerator.html", null ],
      [ "CPError", "interface_c_p_error.html", null ],
      [ "CPEvent", "interface_c_p_event.html", null ],
      [ "CPException", "interface_c_p_exception.html", null ],
      [ "CPFlashMovie", "interface_c_p_flash_movie.html", null ],
      [ "CPFont", "interface_c_p_font.html", null ],
      [ "CPFontManager", "interface_c_p_font_manager.html", null ],
      [ "CPFormatter", "interface_c_p_formatter.html", [
        [ "CPByteCountFormatter", "interface_c_p_byte_count_formatter.html", null ],
        [ "CPDateFormatter", "interface_c_p_date_formatter.html", null ],
        [ "CPNumberFormatter", "interface_c_p_number_formatter.html", null ]
      ] ],
      [ "CPGradient", "interface_c_p_gradient.html", null ],
      [ "CPGraphicsContext", "interface_c_p_graphics_context.html", null ],
      [ "CPImage", "interface_c_p_image.html", null ],
      [ "CPIndexPath", "interface_c_p_index_path.html", null ],
      [ "CPIndexSet", "interface_c_p_index_set.html", [
        [ "CPMutableIndexSet", "class_c_p_mutable_index_set.html", null ]
      ] ],
      [ "CPInvocation", "interface_c_p_invocation.html", null ],
      [ "CPJSONPConnection", "interface_c_p_j_s_o_n_p_connection.html", null ],
      [ "CPKeyBinding", "interface_c_p_key_binding.html", null ],
      [ "CPLocale", "interface_c_p_locale.html", null ],
      [ "CPMenu", "interface_c_p_menu.html", null ],
      [ "CPMenuItem", "interface_c_p_menu_item.html", null ],
      [ "CPNinePartImage", "class_c_p_nine_part_image.html", null ],
      [ "CPNotification", "interface_c_p_notification.html", null ],
      [ "CPNotificationCenter", "interface_c_p_notification_center.html", null ],
      [ "CPNull", "interface_c_p_null.html", null ],
      [ "CPNumber", "interface_c_p_number.html", [
        [ "CPDecimalNumber", "interface_c_p_decimal_number.html", null ]
      ] ],
      [ "CPOperation", "interface_c_p_operation.html", [
        [ "CPFunctionOperation", "interface_c_p_function_operation.html", null ],
        [ "CPInvocationOperation", "interface_c_p_invocation_operation.html", null ]
      ] ],
      [ "CPOperationQueue", "interface_c_p_operation_queue.html", null ],
      [ "CPPasteboard", "interface_c_p_pasteboard.html", null ],
      [ "CPPlatformWindow", "interface_c_p_platform_window.html", null ],
      [ "CPPredicateEditorRowTemplate", "interface_c_p_predicate_editor_row_template.html", null ],
      [ "CPPropertyListSerialization", "interface_c_p_property_list_serialization.html", null ],
      [ "CPRadioGroup", "class_c_p_radio_group.html", null ],
      [ "CPResponder", "interface_c_p_responder.html", [
        [ "CPApplication", "interface_c_p_application.html", null ],
        [ "CPDocument", "interface_c_p_document.html", null ],
        [ "CPPopover", "interface_c_p_popover.html", null ],
        [ "CPView", "interface_c_p_view.html", [
          [ "CPAccordionView", "interface_c_p_accordion_view.html", null ],
          [ "CPBox", "interface_c_p_box.html", null ],
          [ "CPButtonBar", "interface_c_p_button_bar.html", null ],
          [ "CPClipView", "interface_c_p_clip_view.html", null ],
          [ "CPCollectionView", "interface_c_p_collection_view.html", null ],
          [ "CPControl", "interface_c_p_control.html", [
            [ "CPBrowser", "interface_c_p_browser.html", null ],
            [ "CPButton", "interface_c_p_button.html", [
              [ "CPCheckBox", "interface_c_p_check_box.html", null ],
              [ "CPDisclosureButton", "interface_c_p_disclosure_button.html", null ],
              [ "CPPopUpButton", "interface_c_p_pop_up_button.html", null ],
              [ "CPRadio", "interface_c_p_radio.html", null ]
            ] ],
            [ "CPColorWell", "interface_c_p_color_well.html", null ],
            [ "CPDatePicker", "interface_c_p_date_picker.html", null ],
            [ "CPImageView", "interface_c_p_image_view.html", null ],
            [ "CPLevelIndicator", "interface_c_p_level_indicator.html", null ],
            [ "CPRuleEditor", "interface_c_p_rule_editor.html", [
              [ "CPPredicateEditor", "interface_c_p_predicate_editor.html", null ]
            ] ],
            [ "CPScroller", "interface_c_p_scroller.html", null ],
            [ "CPSegmentedControl", "interface_c_p_segmented_control.html", null ],
            [ "CPSlider", "interface_c_p_slider.html", null ],
            [ "CPStepper", "interface_c_p_stepper.html", null ],
            [ "CPTableView", "interface_c_p_table_view.html", [
              [ "CPOutlineView", "interface_c_p_outline_view.html", null ]
            ] ],
            [ "CPTextField", "interface_c_p_text_field.html", [
              [ "CPComboBox", "interface_c_p_combo_box.html", null ],
              [ "CPSearchField", "interface_c_p_search_field.html", null ],
              [ "CPSecureTextField", "interface_c_p_secure_text_field.html", null ],
              [ "CPTokenField", "interface_c_p_token_field.html", null ]
            ] ]
          ] ],
          [ "CPFlashView", "interface_c_p_flash_view.html", null ],
          [ "CPProgressIndicator", "interface_c_p_progress_indicator.html", null ],
          [ "CPScrollView", "interface_c_p_scroll_view.html", null ],
          [ "CPShadowView", "interface_c_p_shadow_view.html", null ],
          [ "CPSplitView", "interface_c_p_split_view.html", null ],
          [ "CPTableCellView", "interface_c_p_table_cell_view.html", null ],
          [ "CPTableHeaderView", "interface_c_p_table_header_view.html", null ],
          [ "CPTabView", "interface_c_p_tab_view.html", null ],
          [ "CPWebView", "interface_c_p_web_view.html", null ]
        ] ],
        [ "CPViewController", "interface_c_p_view_controller.html", [
          [ "CPCollectionViewItem", "interface_c_p_collection_view_item.html", null ]
        ] ],
        [ "CPWindow", "interface_c_p_window.html", [
          [ "CPPanel", "interface_c_p_panel.html", [
            [ "CPColorPanel", "interface_c_p_color_panel.html", null ],
            [ "CPOpenPanel", "interface_c_p_open_panel.html", null ],
            [ "CPSavePanel", "interface_c_p_save_panel.html", null ]
          ] ]
        ] ],
        [ "CPWindowController", "interface_c_p_window_controller.html", null ]
      ] ],
      [ "CPRunLoop", "interface_c_p_run_loop.html", null ],
      [ "CPScanner", "interface_c_p_scanner.html", null ],
      [ "CPScreen", "interface_c_p_screen.html", null ],
      [ "CPShadow", "interface_c_p_shadow.html", null ],
      [ "CPSortDescriptor", "interface_c_p_sort_descriptor.html", null ],
      [ "CPSound", "interface_c_p_sound.html", null ],
      [ "CPString", "interface_c_p_string.html", null ],
      [ "CPTableColumn", "interface_c_p_table_column.html", null ],
      [ "CPTabViewItem", "interface_c_p_tab_view_item.html", null ],
      [ "CPTheme", "interface_c_p_theme.html", null ],
      [ "CPThemeBlend", "interface_c_p_theme_blend.html", null ],
      [ "CPThreePartImage", "class_c_p_three_part_image.html", null ],
      [ "CPTimer", "interface_c_p_timer.html", null ],
      [ "CPTimeZone", "interface_c_p_time_zone.html", null ],
      [ "CPToolbar", "interface_c_p_toolbar.html", null ],
      [ "CPTreeNode", "interface_c_p_tree_node.html", null ],
      [ "CPUndoManager", "interface_c_p_undo_manager.html", null ],
      [ "CPURL", "interface_c_p_u_r_l.html", null ],
      [ "CPURLConnection", "interface_c_p_u_r_l_connection.html", null ],
      [ "CPURLRequest", "interface_c_p_u_r_l_request.html", null ],
      [ "CPURLResponse", "interface_c_p_u_r_l_response.html", [
        [ "CPHTTPURLResponse", "interface_c_p_h_t_t_p_u_r_l_response.html", null ]
      ] ],
      [ "CPUserDefaults", "interface_c_p_user_defaults.html", null ],
      [ "CPUserDefaultsStore", "class_c_p_user_defaults_store.html", [
        [ "CPUserDefaultsCookieStore", "class_c_p_user_defaults_cookie_store.html", null ],
        [ "CPUserDefaultsLocalStore", "class_c_p_user_defaults_local_store.html", null ]
      ] ],
      [ "CPUserSessionManager", "interface_c_p_user_session_manager.html", null ],
      [ "CPValue", "interface_c_p_value.html", null ],
      [ "CPValueTransformer", "interface_c_p_value_transformer.html", [
        [ "CPIsNilTransformer", "interface_c_p_is_nil_transformer.html", null ],
        [ "CPIsNotNilTransformer", "interface_c_p_is_not_nil_transformer.html", null ],
        [ "CPNegateBooleanTransformer", "interface_c_p_negate_boolean_transformer.html", null ],
        [ "CPUnarchiveFromDataTransformer", "interface_c_p_unarchive_from_data_transformer.html", null ]
      ] ],
      [ "CPWebDAVManager", "interface_c_p_web_d_a_v_manager.html", null ],
      [ "CPWebScriptObject", "interface_c_p_web_script_object.html", null ],
      [ "CPWorkspace", "interface_c_p_workspace.html", null ]
    ] ],
    [ "CPObject(CPArrayKVO)", "category_c_p_object_07_c_p_array_k_v_o_08.html", null ],
    [ "CPObject(CPCibLoading)", "category_c_p_object_07_c_p_cib_loading_08.html", null ],
    [ "CPObject(CPCoding)", "category_c_p_object_07_c_p_coding_08.html", null ],
    [ "CPObject(CPDelayedPerform)", "category_c_p_object_07_c_p_delayed_perform_08.html", null ],
    [ "CPObject(CPKeyValueCoding)", "category_c_p_object_07_c_p_key_value_coding_08.html", null ],
    [ "CPObject(CPSetKVO)", "category_c_p_object_07_c_p_set_k_v_o_08.html", null ],
    [ "CPObject(KeyValueBindingCreation)", "category_c_p_object_07_key_value_binding_creation_08.html", null ],
    [ "CPObject(KeyValueObserving)", "category_c_p_object_07_key_value_observing_08.html", null ],
    [ "<CPObject>", "protocol_c_p_object-p.html", [
      [ "<CPAlertDelegate>", "protocol_c_p_alert_delegate-p.html", null ],
      [ "<CPAnimationDelegate>", "protocol_c_p_animation_delegate-p.html", null ],
      [ "<CPApplicationDelegate>", "protocol_c_p_application_delegate-p.html", null ],
      [ "<CPBrowserDelegate>", "protocol_c_p_browser_delegate-p.html", null ],
      [ "<CPCacheDelegate>", "protocol_c_p_cache_delegate-p.html", null ],
      [ "<CPCollectionViewDelegate>", "protocol_c_p_collection_view_delegate-p.html", null ],
      [ "<CPComboBoxDataSource>", "protocol_c_p_combo_box_data_source-p.html", null ],
      [ "<CPComboBoxDelegate>", "protocol_c_p_combo_box_delegate-p.html", null ],
      [ "<CPControlTextEditingDelegate>", "protocol_c_p_control_text_editing_delegate-p.html", [
        [ "<CPTextFieldDelegate>", "protocol_c_p_text_field_delegate-p.html", null ]
      ] ],
      [ "<CPImageDelegate>", "protocol_c_p_image_delegate-p.html", null ],
      [ "<CPMenuDelegate>", "protocol_c_p_menu_delegate-p.html", null ],
      [ "<CPOutlineViewDataSource>", "protocol_c_p_outline_view_data_source-p.html", null ],
      [ "<CPOutlineViewDelegate>", "protocol_c_p_outline_view_delegate-p.html", null ],
      [ "<CPPopoverDelegate>", "protocol_c_p_popover_delegate-p.html", null ],
      [ "<CPRuleEditorDelegate>", "protocol_c_p_rule_editor_delegate-p.html", null ],
      [ "<CPScrollViewDelegate>", "protocol_c_p_scroll_view_delegate-p.html", null ],
      [ "<CPSoundDelegate>", "protocol_c_p_sound_delegate-p.html", null ],
      [ "<CPSplitViewDelegate>", "protocol_c_p_split_view_delegate-p.html", null ],
      [ "<CPTableViewDataSource>", "protocol_c_p_table_view_data_source-p.html", null ],
      [ "<CPTableViewDelegate>", "protocol_c_p_table_view_delegate-p.html", null ],
      [ "<CPTabViewDelegate>", "protocol_c_p_tab_view_delegate-p.html", null ],
      [ "<CPTokenFieldDelegate>", "protocol_c_p_token_field_delegate-p.html", null ],
      [ "<CPToolbarDelegate>", "protocol_c_p_toolbar_delegate-p.html", null ],
      [ "<CPWindowDelegate>", "protocol_c_p_window_delegate-p.html", null ]
    ] ],
    [ "CPObjectController(CPCoding)", "category_c_p_object_controller_07_c_p_coding_08.html", null ],
    [ "CPOpenPanel(CPSynthesizedAccessors)", "category_c_p_open_panel_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPOperationQueue(CPSynthesizedAccessors)", "category_c_p_operation_queue_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPOutlineView(CPCoding)", "category_c_p_outline_view_07_c_p_coding_08.html", null ],
    [ "CPPopover(CPCoding)", "category_c_p_popover_07_c_p_coding_08.html", null ],
    [ "CPPopover(CPSynthesizedAccessors)", "category_c_p_popover_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPPopover(Deprecated)", "category_c_p_popover_07_deprecated_08.html", null ],
    [ "CPPopUpButton(BindingSupport)", "category_c_p_pop_up_button_07_binding_support_08.html", null ],
    [ "CPPopUpButton(CPCoding)", "category_c_p_pop_up_button_07_c_p_coding_08.html", null ],
    [ "CPPredicate", null, [
      [ "CPComparisonPredicate", "interface_c_p_comparison_predicate.html", null ],
      [ "CPCompoundPredicate", "interface_c_p_compound_predicate.html", null ]
    ] ],
    [ "CPProgressIndicator(CPCoding)", "category_c_p_progress_indicator_07_c_p_coding_08.html", null ],
    [ "CPPropertyListSerialization(Deprecated)", "category_c_p_property_list_serialization_07_deprecated_08.html", null ],
    [ "CPProxy", "interface_c_p_proxy.html", null ],
    [ "CPRadio(CPCoding)", "category_c_p_radio_07_c_p_coding_08.html", null ],
    [ "CPRadioGroup(BindingSupport)", "category_c_p_radio_group_07_binding_support_08.html", null ],
    [ "CPRadioGroup(CPCoding)", "category_c_p_radio_group_07_c_p_coding_08.html", null ],
    [ "CPRadioGroup(CPSynthesizedAccessors)", "category_c_p_radio_group_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPResponder(CPCoding)", "category_c_p_responder_07_c_p_coding_08.html", null ],
    [ "CPRunLoop(CPDelayedPerform)", "category_c_p_run_loop_07_c_p_delayed_perform_08.html", null ],
    [ "CPSavePanel(CPSynthesizedAccessors)", "category_c_p_save_panel_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPScroller(CPCoding)", "category_c_p_scroller_07_c_p_coding_08.html", null ],
    [ "CPScroller(CPSynthesizedAccessors)", "category_c_p_scroller_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPScroller(Deprecated)", "category_c_p_scroller_07_deprecated_08.html", null ],
    [ "CPScrollView(CPCoding)", "category_c_p_scroll_view_07_c_p_coding_08.html", null ],
    [ "CPSearchField(CPCoding)", "category_c_p_search_field_07_c_p_coding_08.html", null ],
    [ "CPSegmentedControl(BindingSupport)", "category_c_p_segmented_control_07_binding_support_08.html", null ],
    [ "CPSegmentedControl(CPCoding)", "category_c_p_segmented_control_07_c_p_coding_08.html", null ],
    [ "CPSegmentedControl(CPSynthesizedAccessors)", "category_c_p_segmented_control_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPSet", null, [
      [ "CPMutableSet", "interface_c_p_mutable_set.html", null ]
    ] ],
    [ "CPSet(CPKeyValueCoding)", "category_c_p_set_07_c_p_key_value_coding_08.html", null ],
    [ "CPShadow(CPSynthesizedAccessors)", "category_c_p_shadow_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPSlider(CPCoding)", "category_c_p_slider_07_c_p_coding_08.html", null ],
    [ "CPSlider(Deprecated)", "category_c_p_slider_07_deprecated_08.html", null ],
    [ "CPSortDescriptor(CPCoding)", "category_c_p_sort_descriptor_07_c_p_coding_08.html", null ],
    [ "CPSound(CPSoundDelegate)", "category_c_p_sound_07_c_p_sound_delegate_08.html", null ],
    [ "CPSound(CPSynthesizedAccessors)", "category_c_p_sound_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPSplitView(CPCoding)", "category_c_p_split_view_07_c_p_coding_08.html", null ],
    [ "CPSplitView(CPSplitViewDelegate)", "category_c_p_split_view_07_c_p_split_view_delegate_08.html", null ],
    [ "CPStepper(CPCoding)", "category_c_p_stepper_07_c_p_coding_08.html", null ],
    [ "CPStepper(CPSynthesizedAccessors)", "category_c_p_stepper_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPString(CPCharacterSetAdditions)", "category_c_p_string_07_c_p_character_set_additions_08.html", null ],
    [ "CPString(CPStringDrawing)", "category_c_p_string_07_c_p_string_drawing_08.html", null ],
    [ "CPString(CPTextFieldAdditions)", "category_c_p_string_07_c_p_text_field_additions_08.html", null ],
    [ "CPString(JSON)", "category_c_p_string_07_j_s_o_n_08.html", null ],
    [ "CPString(UUID)", "category_c_p_string_07_u_u_i_d_08.html", null ],
    [ "CPTableCellView(CPSynthesizedAccessors)", "category_c_p_table_cell_view_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPTableColumn(Bindings)", "category_c_p_table_column_07_bindings_08.html", null ],
    [ "CPTableColumn(CPCoding)", "category_c_p_table_column_07_c_p_coding_08.html", null ],
    [ "CPTableColumn(CPSynthesizedAccessors)", "category_c_p_table_column_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPTableColumn(NSInCompatibility)", "category_c_p_table_column_07_n_s_in_compatibility_08.html", null ],
    [ "CPTableContentBinder(CPSynthesizedAccessors)", "category_c_p_table_content_binder_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPTableHeaderView(CPCoding)", "category_c_p_table_header_view_07_c_p_coding_08.html", null ],
    [ "CPTableHeaderView(CPSynthesizedAccessors)", "category_c_p_table_header_view_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPTableHeaderView(CPTableHeaderViewPrivate)", "category_c_p_table_header_view_07_c_p_table_header_view_private_08.html", null ],
    [ "CPTableView(Bindings)", "category_c_p_table_view_07_bindings_08.html", null ],
    [ "CPTableView(CPCoding)", "category_c_p_table_view_07_c_p_coding_08.html", null ],
    [ "CPTableView(CPSynthesizedAccessors)", "category_c_p_table_view_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPTableView(TableViewDataSource)", "category_c_p_table_view_07_table_view_data_source_08.html", null ],
    [ "CPTableView(TableViewDelegate)", "category_c_p_table_view_07_table_view_delegate_08.html", null ],
    [ "CPTabView(CPCoding)", "category_c_p_tab_view_07_c_p_coding_08.html", null ],
    [ "CPTabViewItem(CPCoding)", "category_c_p_tab_view_item_07_c_p_coding_08.html", null ],
    [ "CPTextField(CPCoding)", "category_c_p_text_field_07_c_p_coding_08.html", null ],
    [ "CPTheme(CPCoding)", "category_c_p_theme_07_c_p_coding_08.html", null ],
    [ "CPThemeBlend(CPSynthesizedAccessors)", "category_c_p_theme_blend_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPThreePartImage(CPCoding)", "category_c_p_three_part_image_07_c_p_coding_08.html", null ],
    [ "CPTimeZone(CPSynthesizedAccessors)", "category_c_p_time_zone_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPTokenField(CPCoding)", "category_c_p_token_field_07_c_p_coding_08.html", null ],
    [ "CPTokenField(CPSynthesizedAccessors)", "category_c_p_token_field_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPTokenField(CPTokenFieldDelegate)", "category_c_p_token_field_07_c_p_token_field_delegate_08.html", null ],
    [ "CPToolbar(CPCoding)", "category_c_p_toolbar_07_c_p_coding_08.html", null ],
    [ "CPToolbar(CPSynthesizedAccessors)", "category_c_p_toolbar_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPToolbar(CPToolbarDelegate)", "category_c_p_toolbar_07_c_p_toolbar_delegate_08.html", null ],
    [ "CPTreeNode(CPCoding)", "category_c_p_tree_node_07_c_p_coding_08.html", null ],
    [ "CPTreeNode(CPSynthesizedAccessors)", "category_c_p_tree_node_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPUndoManager(CPCoding)", "category_c_p_undo_manager_07_c_p_coding_08.html", null ],
    [ "CPURL(CPCoding)", "category_c_p_u_r_l_07_c_p_coding_08.html", null ],
    [ "CPURL(SOP)", "category_c_p_u_r_l_07_s_o_p_08.html", null ],
    [ "CPURLConnection(CPSynthesizedAccessors)", "category_c_p_u_r_l_connection_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPURLConnection(Deprecated)", "category_c_p_u_r_l_connection_07_deprecated_08.html", null ],
    [ "CPURLRequest(CPCopying)", "category_c_p_u_r_l_request_07_c_p_copying_08.html", null ],
    [ "CPURLRequest(CPSynthesizedAccessors)", "category_c_p_u_r_l_request_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPUserDefaultsController(CPCoding)", "category_c_p_user_defaults_controller_07_c_p_coding_08.html", null ],
    [ "CPUserDefaultsController(CPSynthesizedAccessors)", "category_c_p_user_defaults_controller_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPUserDefaultsStore(CPSynthesizedAccessors)", "category_c_p_user_defaults_store_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPValue(CPCoding)", "category_c_p_value_07_c_p_coding_08.html", null ],
    [ "CPView(CoreAnimationAdditions)", "category_c_p_view_07_core_animation_additions_08.html", null ],
    [ "CPView(CPCoding)", "category_c_p_view_07_c_p_coding_08.html", null ],
    [ "CPView(CPSynthesizedAccessors)", "category_c_p_view_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPView(KeyView)", "category_c_p_view_07_key_view_08.html", null ],
    [ "CPView(Scaling)", "category_c_p_view_07_scaling_08.html", null ],
    [ "CPView(Theming)", "category_c_p_view_07_theming_08.html", null ],
    [ "CPViewController(CPCoding)", "category_c_p_view_controller_07_c_p_coding_08.html", null ],
    [ "CPViewController(CPSynthesizedAccessors)", "category_c_p_view_controller_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPWebView(CPCoding)", "category_c_p_web_view_07_c_p_coding_08.html", null ],
    [ "CPWindow(BridgeSupport)", "category_c_p_window_07_bridge_support_08.html", null ],
    [ "CPWindow(CPDraggingAdditions)", "category_c_p_window_07_c_p_dragging_additions_08.html", null ],
    [ "CPWindow(CPSynthesizedAccessors)", "category_c_p_window_07_c_p_synthesized_accessors_08.html", null ],
    [ "CPWindow(CPWindowDelegate)", "category_c_p_window_07_c_p_window_delegate_08.html", null ],
    [ "CPWindow(Deprecated)", "category_c_p_window_07_deprecated_08.html", null ]
];